// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.198
// </auto-generated>
// ------------------------------------------------------------------------------
namespace OpenInBrackets
{
    static class Vsix
    {
        public const string Id = "840408f7-8463-4847-9f38-6e845ef8885a";
        public const string Name = "Open in Brackets";
        public const string Description = @"Adds a menu command that lets you open any solution, project, folder and file in Adobe Brackets Editor.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Naim Hammadi";
        public const string Tags = "Brackets code editor programming";
    }
}
